{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
#
# ConfigMap to load custom SQL files to be executed at deployment time
#
# Note: Custom SQL files are only loaded if apps curam is enabled
#

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sch.names.fullCompName" (list . "hook-customsql") }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "customsql") | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  xmlserver.sql: |
    UPDATE PROPERTIES SET VALUE='{{ .Release.Name }}-xmlserver' WHERE NAME='curam.xmlserver.host';
  {{- if .Values.global.apps.common.persistence.enabled }}
  {{- if .Values.global.apps.common.persistence.jmxstats.enabled }}
  jmxstats.sql: |
    {{- $v := dict "value" .Values.global.apps.common.persistence.jmxstats.timerPeriod }}
    {{- include "apps.value-validation" $v }}
    UPDATE PROPERTIES SET VALUE = '{{ .Values.global.apps.common.persistence.jmxstats.timerPeriod }}' WHERE NAME = 'curam.jmx.output_statistics_timer_period';
    UPDATE PROPERTIES SET VALUE = '/tmp/jmx' WHERE NAME = 'curam.jmx.output_statistics_timer_folder';
    UPDATE PROPERTIES SET VALUE = 'true'  WHERE NAME = 'curam.jmx.output_statistics_timer_enabled';
  {{- end }}
  {{- end }}
  {{- if .Values.properties }}
  properties.sql: |
    {{- range $key, $value := .Values.properties }}
    {{- $v := dict "value" $value }}
    {{- include "apps.value-validation" $v }}
    UPDATE PROPERTIES SET VALUE = '{{ $value }}' WHERE NAME = '{{ $key }}';
    {{- end }}
  {{- end }}
