{{- include "sch.config.init" (list . "mqserver.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2019,2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sch.names.fullCompName" (list . "cm")  }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . ) | nindent 4 }}
data:
  config.mqsc: |
    DEFINE QLOCAL(QN.CURAMDEADMESSAGEQUEUE) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE
    DEFINE QLOCAL(QN.WORKFLOWERROR) BOTHRESH(5) BOQNAME(QN.CURAMDEADMESSAGEQUEUE) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE
    DEFINE QLOCAL(QN.WORKFLOWENACTMENT) BOTHRESH(5) BOQNAME(QN.WORKFLOWERROR) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE
    DEFINE QLOCAL(QN.WORKFLOWACTIVITY) BOTHRESH(5) BOQNAME(QN.WORKFLOWERROR) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE
    DEFINE QLOCAL(QN.DPERROR) BOTHRESH(5) BOQNAME(QN.CURAMDEADMESSAGEQUEUE) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE
    DEFINE QLOCAL(QN.DPENACTMENT) BOTHRESH(5) BOQNAME(QN.DPERROR) CLWLUSEQ (ANY) DEFBIND (NOTFIXED) REPLACE

    ALTER QMGR CHLAUTH(DISABLED) DEADQ(QN.CURAMDEADMESSAGEQUEUE)

    DEFINE CHANNEL(MQ_CHN_PROD) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCIPH (TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL ('ibmwebspheremq{{ .Values.global.mq.queueManager.name | lower }}') SSLCAUTH (OPTIONAL) REPLACE
    DEFINE CHANNEL(MQ_CHN_CONS) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCIPH (TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL ('ibmwebspheremq{{ .Values.global.mq.queueManager.name | lower }}') SSLCAUTH (OPTIONAL) REPLACE

    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.DPENACTMENT') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.DPERROR') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWACTIVITY') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWENACTMENT') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWERROR') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.CURAMDEADMESSAGEQUEUE') PRINCIPAL('app') AUTHADD(ALL)

    SET AUTHREC OBJTYPE(CHANNEL) PROFILE('MQ_CHN_PROD') PRINCIPAL('app') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(CHANNEL) PROFILE('MQ_CHN_CONS') PRINCIPAL('app') AUTHADD(ALL)

  {{- if and ($.Values.global.mq.metrics.enabled) ($.Values.global.mq.metrics.additionalMetrics) }}
    SET CHLAUTH('SYSTEM.*') TYPE(ADDRESSMAP) ADDRESS(*) ACTION(REMOVE)
    SET AUTHREC OBJTYPE(QMGR) PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.DPENACTMENT') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.DPERROR') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWACTIVITY') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWENACTMENT') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.WORKFLOWERROR') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('QN.CURAMDEADMESSAGEQUEUE') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('SYSTEM.ADMIN.COMMAND.QUEUE') PRINCIPAL('admin') AUTHADD(ALL)
    SET AUTHREC OBJTYPE(QUEUE) PROFILE('SYSTEM.DEFAULT.MODEL.QUEUE') PRINCIPAL('admin') AUTHADD(ALL)

    ALTER QMGR PERFMEV(ENABLED)
    ALTER QLOCAL(QN.CURAMDEADMESSAGEQUEUE) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
    ALTER QLOCAL(QN.WORKFLOWERROR) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
    ALTER QLOCAL(QN.WORKFLOWENACTMENT) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
    ALTER QLOCAL(QN.WORKFLOWACTIVITY) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
    ALTER QLOCAL(QN.DPERROR) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
    ALTER QLOCAL(QN.DPENACTMENT) QDEPTHHI(80) QDPHIEV(ENABLED) QDEPTHLO(20) QDPLOEV(ENABLED) QDPMAXEV(ENABLED)
  {{- end }}

{{ $apps := .Values.global.apps.config }}
{{- range $name, $app := $apps }}
{{- if and ($app.enabled) (not (hasKey $app "mqConnectionNameList")) }}
  channel_{{$name}}.mqsc: |
    DEFINE CHANNEL(MQ_CHN_PROD) CHLTYPE(CLNTCONN) TRPTYPE(TCP) CONNAME('{{ $.Release.Name }}-mqserver-{{ $name }}') QMNAME({{ $.Values.global.mq.queueManager.name }}) SSLCIPH (TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL ('ibmwebspheremq{{ $.Values.global.mq.queueManager.name | lower }}') REPLACE
    DEFINE CHANNEL(MQ_CHN_CONS) CHLTYPE(CLNTCONN) TRPTYPE(TCP) CONNAME('{{ $.Release.Name }}-mqserver-{{ $name }}') QMNAME({{ $.Values.global.mq.queueManager.name }}) SSLCIPH (TLS_RSA_WITH_AES_128_CBC_SHA256) CERTLABL ('ibmwebspheremq{{ $.Values.global.mq.queueManager.name | lower }}') REPLACE
    {{- if eq $name "curam" }}
    DEFINE TOPIC (CURAMCACHEINVALIDATIONTOPIC) TOPICSTR (CURAMCACHEINVALIDATIONTOPIC) REPLACE
    SET AUTHREC OBJTYPE(TOPIC) PROFILE('CURAMCACHEINVALIDATIONTOPIC') PRINCIPAL('app') AUTHADD(ALL)
    {{- end }}
{{- end }}
{{- end }}
