{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2019,2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-dbconn-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
data:
  server_resources_jdbc.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server JDBC Resource Configuration">

      <!-- ========================== Libraries ========================== -->
      <library id="DBDriverLib">
        <fileset dir="${shared.resource.dir}/drivers" includes="{{ include "apps.dbdriver.jars" .Values.global.database }}" />
      </library>

      <!-- ========================== Drivers ========================== -->
      <jdbcDriver id="CuramJdbcDriver" libraryRef="DBDriverLib" />

      <!-- ========================== Data Sources ========================== -->
      <dataSource id="curamdb" jndiName="jdbc/curamdb"
        isolationLevel="TRANSACTION_REPEATABLE_READ"
        jdbcDriverRef="CuramJdbcDriver" type="javax.sql.XADataSource"
        statementCacheSize="${env.DS_CURAMDB_CACHE_SIZE}">
        {{- include "apps.dsprops.fragment" (list . "CURAMDB") | nindent 8 }}
      </dataSource>

      <dataSource id="DefaultDataSource" jndiName="jdbc/curamtimerdb"
        isolationLevel="TRANSACTION_REPEATABLE_READ"
        jdbcDriverRef="CuramJdbcDriver" type="javax.sql.XADataSource"
        statementCacheSize="${env.DS_CURAMTIMERDB_CACHE_SIZE}">
        {{- include "apps.dsprops.fragment" (list . "CURAMTIMERDB") | nindent 8 }}
      </dataSource>

      <databaseStore id="EJBTimerDatabaseStore" tablePrefix="EJBTIMER_${env.POD_TIMER_TYPE}_" dataSourceRef="DefaultDataSource" createTables="true"/>
      <persistentExecutor id="defaultEJBPersistentTimerExecutor"
        taskStoreRef="EJBTimerDatabaseStore"
        missedTaskThreshold="{{ .Values.persistentTimers.missedTaskThreshold }}"
        pollInterval="{{ .Values.persistentTimers.pollInterval }}"
        initialPollDelay="{{ .Values.persistentTimers.initialPollDelay }}"
        {{- if .Values.persistentTimers.pollSize }}
        pollSize="{{ .Values.persistentTimers.pollSize }}"
        {{- end }}
      />
      <ejbContainer>
        <timerService persistentExecutorRef="defaultEJBPersistentTimerExecutor"
          missedPersistentTimerAction="{{ .Values.persistentTimers.missedPersistentTimerAction }}"
          lateTimerThreshold="{{ .Values.persistentTimers.lateTimerThreshold }}"
        />
      </ejbContainer>

    </server>
