{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2021 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-openid-cm
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
data:
  server_openid.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="OpenID Configuration">

      <featureManager>
        <feature>openidConnectClient-1.0</feature>
        <feature>transportSecurity-1.0</feature>
      </featureManager>

      <authFilter id="jwtAuthFilter">
        <requestHeader id="authHeader" name="Authorization" value="Bearer" matchType="contains"/>
      </authFilter>

      <!-- Default "LtpaToken2" cookie name is ignored when OIDC is enabled. -->
      <webAppSecurity
        ssoRequiresSSL="true"
        ssoCookieName="SPMLtpa2Cookie"
      />

      <openidConnectClient
        id="RS"
        inboundPropagation="supported"
        issuerIdentifier="{{ .Values.jwtConfig.issuerIdentifier }}"
        audiences="ALL_AUDIENCES"
        signatureAlgorithm="RS256"
        disableLtpaCookie="false"
        allowCustomCacheKey="false"
        trustStoreRef="defaultKeyStore"
        trustAliasName="jwtcertalias"
        realmName="BasicRegistry"
        authFilterRef="jwtAuthFilter"
      />

    </server>

  JWTKeystore.properties: |
    # Placed by Kubernetes Configmap.
    jwt.keystore.filename=jwtkeystore.p12
    jwt.keystore.location=/config/resources
    jwt.keystore.password=password
    jwt.keystore.type=PKCS12
    jwt.key.alias=jwtkeyalias
