{{- include "sch.config.init" (list . "apps.sch.chart.config.values") -}}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-messaging-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sch.metadata.labels.standard" (list . "") | nindent 4 }}
data:
  server_resources_messaging.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server Messaging (JMS) Resource Configuration">

      <featureManager>
        <feature>wmqJmsClient-2.0</feature>
        <feature>transportSecurity-1.0</feature>
      </featureManager>

      <messagingEngine>
        <queue id="QN.DPENACTMENT" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.DPERROR" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWENACTMENT" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWACTIVITY" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.WORKFLOWERROR" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <queue id="QN.CURAMDEADMESSAGEQUEUE" forceReliability="ReliablePersistent" maxMessageDepth="5000" />
        <topicSpace id="Default.Topic.Space" forceReliability="ReliablePersistent" maintainStrictOrder="true" maxMessageDepth="5000" />
      </messagingEngine>

      <variable name="wmqJmsClient.rar.location" value="/opt/wmq/wmq.jmsra.rar"/>
      <variable name="mqName" value="${env.MQ_QMGR_NAME}"/>
      <variable name="channel" value="${env.MQ_CHANNEL_NAME}"/>
      <variable name="userName" value="${env.MQ_CONN_USER}"/>
      {{- if .Values.global.mq.useConnectionNameList }}
      <variable name="connectionNameList" value="${env.MQ_CONN_NAME_LIST}"/>
      {{- else }}
      <variable name="mqHostName" value="${env.MQ_HOST_NAME}"/>
      <variable name="listenerPort" value="${env.MQ_CHANNEL_PORT}"/>
      {{- end }}

      <jmsActivationSpec id="eis/DPEnactmentAS" maxEndpoints="${env.CM_JMS_DPENACTMENT_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "DPEnactment") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="DPEnactment" jndiName="jms/DPEnactment">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.DPENACTMENT" />
      </jmsQueue>

      <jmsActivationSpec id="eis/DPErrorAS" maxEndpoints="${env.CM_JMS_DPERROR_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "DPError") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="DPError" jndiName="jms/DPError">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.DPERROR" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowEnactmentAS" maxEndpoints="${env.CM_JMS_WORKFLOWENACTMENT_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "WorkflowEnactment") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="WorkflowEnactment" jndiName="jms/WorkflowEnactment">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWENACTMENT" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowActivityAS" maxEndpoints="${env.CM_JMS_WORKFLOWACTIVITY_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "WorkflowActivity") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="WorkflowActivity" jndiName="jms/WorkflowActivity">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWACTIVITY" />
      </jmsQueue>

      <jmsActivationSpec id="eis/WorkflowErrorAS" maxEndpoints="${env.CM_JMS_WORKFLOWERROR_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "WorkflowError") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="WorkflowError" jndiName="jms/WorkflowError">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.WORKFLOWERROR" />
      </jmsQueue>

      <jmsActivationSpec id="eis/CuramDeadMessageQueueAS" maxEndpoints="${env.CM_JMS_CURAMDEADMESSAGEQUEUE_MAXENDPOINTS}">
        {{- include "jms.queueActivationSpec" (list . "CuramDeadMessageQueue") | nindent 8 }}
      </jmsActivationSpec>

      <jmsQueue id="CuramDeadMessageQueue" jndiName="jms/CuramDeadMessageQueue">
        <properties.wmqJms persistence="PERS" baseQueueName="QN.CURAMDEADMESSAGEQUEUE" />
      </jmsQueue>

      <!-- Activation Spec for CuramCacheInvalidationTopic in EJB Infrastructure Module -->
      <jmsActivationSpec id="eis/CuramCacheInvalidationTopicAS">
        {{- include "jms.topicActivationSpec" . | nindent 8 }}
      </jmsActivationSpec>

      <!-- Activation Spec for CuramCacheInvalidationTopic in Invalidation Module -->
      <jmsActivationSpec id="Curam/InvalidationModule/CuramCacheInvalidationTopicMDB">
        {{- include "jms.topicActivationSpec" . | nindent 8 }}
      </jmsActivationSpec>

      <jmsTopic id="CuramCacheInvalidationTopic" jndiName="jms/CuramCacheInvalidationTopic">
        <properties.wmqJms baseTopicName="CURAMCACHEINVALIDATIONTOPIC" />
      </jmsTopic>

      <jmsConnectionFactory
        id="CuramQueueConnectionFactory"
        jndiName="jms/CuramQueueConnectionFactory"
        connectionManagerRef="ConMgr6">

        {{- include "jms.queueConnectionFactory" . | nindent 8 }}
      </jmsConnectionFactory>
      <connectionManager
        id="ConMgr6"
        maxPoolSize="${env.CM_MQ_MAXPOOLSIZE}"
        minPoolSize="${env.CM_MQ_MINPOOLSIZE}"
        numConnectionsPerThreadLocal="${env.CM_JMS_NUM_CONNECTIONS_PER_THREAD_LOCAL}"
        maxConnectionsPerThread="${env.CM_JMS_MAX_CONNECTIONS_PER_THREAD}"
      />

      <jmsTopicConnectionFactory
        id="CuramTopicConnectionFactory"
        jndiName="jms/CuramTopicConnectionFactory">

        {{- include "jms.topicConnectionFactory" . | nindent 8 }}
      </jmsTopicConnectionFactory>

    </server>
