{{- if and .Values.global.ingress.enabled (not (.Capabilities.APIVersions.Has "route.openshift.io/v1")) }}
---
###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "spm.labels" . | indent 4 }}
  annotations:
    ingress.bluemix.net/ssl-services: {{ include "sslServicesChain" . }}
    ingress.bluemix.net/sticky-cookie-services: {{ include "stickyCookieServicesChain" . }}
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/session-cookie-path: /
  {{- with .Values.global.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if or .Values.global.ingress.tlsSecretName .Values.global.ingress.generateCert }}
  tls:
    - hosts:
        -  {{ required "When ingress is enabled, you must provide a value for ingress.hostname" .Values.global.ingress.hostname }}
      {{- if .Values.global.ingress.generateCert }}
      secretName: {{ .Release.Name }}-tls
      {{- else }}
      secretName: {{ .Values.global.ingress.tlsSecretName }}
      {{- end }}
  {{- end }}
  rules:
    - host: {{ required "When ingress is enabled, you must provide a value for ingress.hostname" .Values.global.ingress.hostname }}
      http:
        paths:
          {{- range $name, $app := .Values.global.apps.config }}
          {{- if and $app.enabled $app.ingressPath }}
          - path: {{ $app.ingressPath }}
            backend:
              serviceName: {{ $.Release.Name }}-apps-{{ $name }}
              servicePort: https
          {{- end }}
          {{- end }}
          {{- if .Values.global.ceApp.imageName }}
          - path: {{ .Values.global.ceApp.ingressPath | default "/universal" }}
            backend:
              serviceName: {{ $.Release.Name }}-ce-app
              servicePort: https
          {{- end }}
          {{- if .Values.global.isam.enabled }}
          - path: "/ibm" 
            backend:
              serviceName: {{ $.Release.Name }}-apps-curam
              servicePort: https
          {{- end }}
          - path: {{ .Values.global.ihs.ingressPath | default "/CuramStatic" }}
            backend:
              serviceName: {{ $.Release.Name }}-ihs
              servicePort: https
{{- end }}
