###############################################################################
# Copyright 2019,2020 IBM Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
###############################################################################
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-jms-consumer-security
  namespace: {{ .Release.Namespace }}
data:
  server_security.xml: |
    <?xml version="1.0" encoding="UTF-8"?>
    <!-- Placed by Kubernetes Configmap. -->
    <server description="Server security configuration">

      <ssl clientAuthentication="false" clientAuthenticationSupported="false" id="defaultSSLConfig" keyStoreRef="defaultKeyStore"
          securityLevel="HIGH" sslProtocol="TLSv1.2"  />
      <keyStore id="defaultKeyStore" location="key.jks" password="{xor}Lz4sLCgwLTs=" type="JKS"/>

      <basicRegistry id="basic" realm="BasicRegistry">
        <user name="websphere" password="{xor}KDo9LC83Oi06" />
        <user name="${env.SYSTEM_USER}" password="${env.SYSTEM_PASSWORD}" />

        <group name="everyone"/>
      </basicRegistry>

      <administrator-role>
        <user>websphere</user>
      </administrator-role>

      <authentication id="Basic" cacheEnabled="true"/>
      <authCache initialSize="100" maxSize="50000" timeout="15m"/>

      <library description="Custom login module shared library" filesetRef="registryFileSet" id="customLoginLib" name="customLoginLib"/>
      <fileset dir="${shared.resource.dir}" id="registryFileSet" includes="*.jar"/>

      <jaasLoginContextEntry id="system.WEB_INBOUND" loginModuleRef="myCustomWebInbound,hashtable,userNameAndPassword,certificate" name="system.WEB_INBOUND"/>
      <jaasLoginModule className="curam.util.security.CuramLoginModule" controlFlag="REQUIRED" id="myCustomWebInbound" libraryRef="customLoginLib">
        <options
          exclude_usernames="websphere,${env.SYSTEM_USER}"
          login_trace="{{ .Values.global.apps.common.loginTrace | default "true" }}"
        />
      </jaasLoginModule>

      <jaasLoginContextEntry id="system.DEFAULT" loginModuleRef="myCustomDefault,hashtable,userNameAndPassword,certificate" name="system.DEFAULT"/>
      <jaasLoginModule className="curam.util.security.CuramLoginModule" controlFlag="REQUIRED" id="myCustomDefault" libraryRef="customLoginLib">
        <options
          exclude_usernames="websphere,${env.SYSTEM_USER}"
          login_trace="{{ .Values.global.apps.common.loginTrace | default "true" }}"
        />
      </jaasLoginModule>

      <orb id="defaultOrb">
        <serverPolicy.csiv2>
          <layers>
            <authenticationLayer mechanisms="LTPA" establishTrustInClient="Supported"/>
          </layers>
        </serverPolicy.csiv2>
      </orb>

    </server>
